# Generated by Django 5.0.9 on 2026-06-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meterreading',
            new_name='meter_readi_assignm_0da9b4_idx',
            old_name='meter_readi_assignm_8859ee_idx',
        ),
        migrations.RenameIndex(
            model_name='meterreading',
            new_name='meter_readi_agent_i_99ab51_idx',
            old_name='meter_readi_agent_i_8d0b5f_idx',
        ),
        migrations.RenameIndex(
            model_name='meterreading',
            new_name='meter_readi_result_9ddb24_idx',
            old_name='meter_readi_result_045f34_idx',
        ),
        migrations.RenameIndex(
            model_name='terrainassignment',
            new_name='terrain_ass_agent_i_efcd08_idx',
            old_name='terrain_ass_agent__601d77_idx',
        ),
        migrations.RenameIndex(
            model_name='terrainassignment',
            new_name='terrain_ass_import__02deb8_idx',
            old_name='terrain_ass_import__e7b9e9_idx',
        ),
        migrations.RenameIndex(
            model_name='terrainassignment',
            new_name='terrain_ass_client__18828f_idx',
            old_name='terrain_ass_client__207f04_idx',
        ),
    ]
