# Generated by Django 5.0.9 on 2026-05-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('code', models.CharField(help_text="Code numérique du centre (ex: '42').", max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text="Nom usuel du centre (ex: 'CARREFOUR2').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centre SNDE',
                'verbose_name_plural': 'Centres SNDE',
                'db_table': 'centres',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(help_text='Identifiant complet : NomCentre_SecteurZfill2_TourneeZfill2.', max_length=150)),
                ('centre_nom', models.CharField(max_length=100)),
                ('secteur', models.CharField(max_length=10)),
                ('tournee', models.CharField(max_length=10)),
                ('nb_clients', models.IntegerField()),
                ('nb_entreprises', models.IntegerField()),
                ('nb_domestiques', models.IntegerField()),
                ('score_moyen', models.FloatField()),
                ('score_max', models.FloatField()),
                ('score_total', models.FloatField()),
                ('anciennete_moyenne', models.FloatField()),
                ('solde_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('solde_moyen', models.DecimalField(decimal_places=2, max_digits=14)),
                ('arrieres_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('priorite_zone', models.FloatField(help_text='score_moyen × nb_clients (intensité × volume).')),
                ('priorite', models.CharField(choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Faible', 'Faible')], help_text='Catégorisation auto-adaptative par quantiles 75/50.', max_length=10)),
                ('rang', models.IntegerField(help_text="Position dans le classement de l'import (1 = plus prioritaire).")),
                ('import_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='imports.fabimport')),
            ],
            options={
                'verbose_name': 'Zone agrégée',
                'verbose_name_plural': 'Zones agrégées',
                'db_table': 'zones',
                'ordering': ['import_ref', 'rang'],
                'indexes': [models.Index(fields=['import_ref', 'priorite_zone'], name='zones_import__cc083e_idx'), models.Index(fields=['import_ref', 'priorite'], name='zones_import__de49f0_idx'), models.Index(fields=['import_ref', 'centre_nom'], name='zones_import__ea3a84_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('import_ref', 'zone_id'), name='zone_unique_per_import'),
        ),
    ]
