# Generated by Django 5.0.9 on 2026-05-11 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_montant', models.FloatField(default=0.4, help_text='Poids de la composante Montant (solde normalisé min-max).')),
                ('weight_anciennete', models.FloatField(default=0.25, help_text='Poids de la composante Ancienneté (jours_impaye / seuil).')),
                ('weight_historique', models.FloatField(default=0.2, help_text='Poids de la composante Historique (jours_sans_paiement / seuil).')),
                ('weight_arrieres', models.FloatField(default=0.15, help_text='Poids de la composante Arriérés (arrieres / solde).')),
                ('coef_domestique', models.FloatField(default=1.0, help_text='Multiplicateur du score pour les clients Domestique.')),
                ('coef_entreprise', models.FloatField(default=1.2, help_text='Multiplicateur du score pour les clients Entreprise.')),
                ('threshold_days', models.IntegerField(default=180, help_text='Jours au-delà desquels Ancienneté/Historique sont plafonnés à 1.0.')),
                ('priority_quantile_high', models.FloatField(default=0.75, help_text='Quantile à partir duquel un score est en priorité Haute.')),
                ('priority_quantile_med', models.FloatField(default=0.5, help_text='Quantile à partir duquel un score est en priorité Moyenne.')),
                ('is_active', models.BooleanField(default=False, help_text='Configuration utilisée pour les nouveaux imports + recalculs.')),
                ('description', models.CharField(blank=True, help_text="Note libre : 'Test plus de poids sur ancienneté', etc.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoring_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration de scoring',
                'verbose_name_plural': 'Configurations de scoring',
                'db_table': 'scoring_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='scoringconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='scoring_config_only_one_active'),
        ),
    ]
