# Generated by Django 5.0.9 on 2026-05-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_abonnement', models.CharField(max_length=20)),
                ('nom_client', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('activite_client', models.CharField(blank=True, max_length=100)),
                ('type_client', models.CharField(choices=[('Domestique', 'Domestique'), ('Entreprise', 'Entreprise')], max_length=20)),
                ('code_centre', models.CharField(max_length=10)),
                ('centre_nom', models.CharField(max_length=100)),
                ('secteur_facturation', models.CharField(max_length=10)),
                ('tournee_releve', models.CharField(max_length=10)),
                ('releveur_1', models.CharField(blank=True, max_length=20)),
                ('zone', models.CharField(help_text='NomCentre_SecteurZfill2_TourneeZfill2 — joint à zones.Zone.zone_id.', max_length=150)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_facture', models.DecimalField(decimal_places=2, max_digits=14)),
                ('arrieres', models.DecimalField(decimal_places=2, help_text='solde - montant_facture (clipé à 0 si négatif).', max_digits=14)),
                ('date_facture', models.DateField(blank=True, null=True)),
                ('date_dernier_paiement', models.DateField(blank=True, null=True)),
                ('jours_impaye', models.IntegerField()),
                ('jours_sans_paiement', models.IntegerField()),
                ('code_relance', models.CharField(help_text="V1 : on ne stocke que les clients avec code_relance='1'.", max_length=2)),
                ('montant_norm', models.FloatField()),
                ('anciennete_norm', models.FloatField()),
                ('historique_norm', models.FloatField()),
                ('arrieres_norm', models.FloatField()),
                ('coefficient_type', models.FloatField(help_text='1.00 si Domestique, 1.20 si Entreprise.')),
                ('score_final', models.FloatField()),
                ('priorite', models.CharField(choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Faible', 'Faible')], max_length=10)),
                ('rang', models.IntegerField(help_text="Position dans le classement de l'import (1 = plus prioritaire).")),
                ('import_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='imports.fabimport')),
            ],
            options={
                'verbose_name': 'Client (snapshot import)',
                'verbose_name_plural': 'Clients (snapshot import)',
                'db_table': 'clients',
                'ordering': ['import_ref', 'rang'],
                'indexes': [models.Index(fields=['import_ref', 'score_final'], name='clients_import__0980e7_idx'), models.Index(fields=['import_ref', 'zone'], name='clients_import__4f792c_idx'), models.Index(fields=['import_ref', 'priorite'], name='clients_import__b4f694_idx'), models.Index(fields=['import_ref', 'code_centre'], name='clients_import__0d2736_idx'), models.Index(fields=['reference_abonnement'], name='clients_referen_159fed_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('import_ref', 'reference_abonnement'), name='client_unique_per_import'),
        ),
    ]
