# Generated by Django 5.0.9 on 2026-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_scored',
            field=models.BooleanField(default=False, help_text="True uniquement si code_relance='1' au moment de l'import. Les autres clients sont stockés pour le suivi du cycle/recouvrement mais sans calcul de score."),
        ),
        migrations.AlterField(
            model_name='client',
            name='anciennete_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='arrieres_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_relance',
            field=models.CharField(help_text='0=repos · 4=SMS J+8 · 2=SMS J+48h · 1=coupure immédiate · 3=autre. Voir Notes V1.5 sur le cycle de relance.', max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='coefficient_type',
            field=models.FloatField(blank=True, help_text='1.00 si Domestique, 1.20 si Entreprise.', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='historique_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='montant_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='priorite',
            field=models.CharField(blank=True, choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Faible', 'Faible')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='rang',
            field=models.IntegerField(blank=True, help_text="Position dans le classement de l'import (1 = plus prioritaire).", null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='score_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['import_ref', 'code_relance'], name='clients_import__3b85de_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['import_ref', 'is_scored'], name='clients_import__1b6c05_idx'),
        ),
    ]
