# Generated by Django 5.0.9 on 2026-05-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_scored_alter_client_anciennete_norm_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_import__1b6c05_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_scored',
        ),
    ]
