# Generated by Django 5.0.9 on 2026-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_clients_import__1b6c05_idx_and_more'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='relance_state',
            field=models.CharField(choices=[('normal', 'Normal'), ('sms_j8', 'SMS rappel J+8'), ('grace_j8', 'Grâce J+8'), ('sms_j48h', 'SMS rappel J+48h'), ('grace_j48h', 'Grâce J+48h'), ('cut_off', 'Coupure immédiate'), ('cut_off_fast', 'Coupure (cycle accéléré)'), ('anomaly_overdue', 'Anomalie : coupure manquée'), ('unknown', 'Inconnu')], default='unknown', help_text="État dérivé du cycle de relance, calculé depuis code_relance + dates. Permet de distinguer 'code 0 = normal' vs 'code 0 = en grâce J+8' etc.", max_length=20),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['import_ref', 'relance_state'], name='clients_import__8069d7_idx'),
        ),
    ]
