# Generated by Django 5.0.9 on 2026-05-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_abonnement', models.CharField(max_length=20)),
                ('nom_client', models.CharField(blank=True, max_length=200)),
                ('solde_before', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('solde_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('delta_solde', models.DecimalField(decimal_places=2, help_text='solde_before - solde_after. Positif = solde baissé (paiement probable). Négatif = solde augmenté (nouvelle facturation).', max_digits=14)),
                ('code_before', models.CharField(blank=True, max_length=2)),
                ('code_after', models.CharField(blank=True, max_length=2)),
                ('montant_facture_before', models.DecimalField(blank=True, decimal_places=2, help_text='Pour comparer delta_solde vs montant facture précédente.', max_digits=14, null=True)),
                ('type', models.CharField(choices=[('payment_certain', 'Paiement certain'), ('payment_likely', 'Paiement probable'), ('payment_partial', 'Paiement partiel'), ('adjustment', 'Ajustement / correction'), ('departure', 'Sortie suspecte'), ('new_billing', 'Nouvelle facturation'), ('new_client', 'Nouveau client'), ('no_movement', 'Pas de mouvement')], max_length=20)),
                ('confidence', models.FloatField(help_text='Niveau de confiance dans la classification (0.0 à 1.0).')),
                ('notes', models.TextField(blank=True, help_text="Détails sur la classification (ex: 'delta=montant_facture exact').")),
                ('centre_nom', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, max_length=150)),
                ('date_from', models.DateField(blank=True, help_text="file_date de l'import_from (date du FAB précédent).", null=True)),
                ('date_to', models.DateField(help_text="file_date de l'import_to (date du FAB courant).")),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('import_from', models.ForeignKey(blank=True, help_text='Import précédent (null si nouveau client).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_out', to='imports.fabimport')),
                ('import_to', models.ForeignKey(help_text='Import courant (sur lequel la transition est calculée).', on_delete=django.db.models.deletion.CASCADE, related_name='movements_in', to='imports.fabimport')),
            ],
            options={
                'verbose_name': 'Mouvement client',
                'verbose_name_plural': 'Mouvements clients',
                'db_table': 'client_movements',
                'ordering': ['-date_to', '-delta_solde'],
                'indexes': [models.Index(fields=['import_to', 'type'], name='client_move_import__3c1fb8_idx'), models.Index(fields=['import_to', 'date_to'], name='client_move_import__e4de4e_idx'), models.Index(fields=['reference_abonnement'], name='client_move_referen_0acd6f_idx'), models.Index(fields=['type', 'date_to'], name='client_move_type_b8a8d1_idx')],
            },
        ),
    ]
