# Generated by Django 5.0.9 on 2026-05-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmovement',
            name='type',
            field=models.CharField(choices=[('payment_certain', 'Paiement certain'), ('payment_likely', 'Paiement probable'), ('adjustment', 'Ajustement / correction'), ('departure', 'Sortie suspecte'), ('new_billing', 'Nouvelle facturation'), ('new_client', 'Nouveau client'), ('no_movement', 'Pas de mouvement')], max_length=20),
        ),
    ]
