# Generated by Django 5.0.9 on 2026-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0002_alter_clientmovement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmovement',
            name='date_paiement_after',
            field=models.DateField(blank=True, help_text='date_dernier_paiement du client dans le FAB courant. Si > date_paiement_before, un paiement a été enregistré par SNDE.', null=True),
        ),
        migrations.AddField(
            model_name='clientmovement',
            name='date_paiement_before',
            field=models.DateField(blank=True, help_text='date_dernier_paiement du client dans le FAB précédent.', null=True),
        ),
    ]
