# Generated by Django 5.0.9 on 2026-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0003_clientmovement_date_paiement_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmovement',
            name='skipped_grace',
            field=models.BooleanField(default=False, help_text='True si la transition mène à code 1 sans être passée par code 2 récemment. Indique que SNDE a accéléré le cycle (typique des clients à fort solde).'),
        ),
    ]
