# Generated by Django 5.0.9 on 2026-06-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0004_clientmovement_skipped_grace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBehavior',
            fields=[
                ('reference_abonnement', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=200)),
                ('type_client', models.CharField(choices=[('Domestique', 'Domestique'), ('Entreprise', 'Entreprise')], max_length=20)),
                ('last_seen_date', models.DateField(blank=True, help_text='Date du FAB le + récent où le client était présent.', null=True)),
                ('last_centre_nom', models.CharField(blank=True, max_length=100)),
                ('last_zone', models.CharField(blank=True, max_length=150)),
                ('last_releveur', models.CharField(blank=True, max_length=20)),
                ('nb_imports_seen', models.IntegerField(help_text="Nombre total d'apparitions dans des FABs.")),
                ('nb_payments', models.IntegerField(help_text='Nombre de mouvements PAYMENT_CERTAIN + PAYMENT_LIKELY.')),
                ('nb_code_1', models.IntegerField(help_text="Nombre de fois passé en code_relance='1' (coupures ordonnées).")),
                ('nb_new_billings', models.IntegerField(help_text='Nombre de NEW_BILLING (factures supplémentaires).')),
                ('avg_solde', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_solde', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Somme des delta_solde des PAYMENT_* (montant payé estimé).', max_digits=16)),
                ('avg_jours_impaye', models.FloatField(blank=True, help_text='Moyenne des jours_impaye sur tous les snapshots.', null=True)),
                ('payment_freq_score', models.FloatField(help_text='Score fréquence paiement (taux paiements / nb_factures).')),
                ('promptness_score', models.FloatField(help_text='Score promptitude (inverse du délai moyen).')),
                ('code_1_score', models.FloatField(help_text='Score code 1 (100 - fréquence des coupures ordonnées).')),
                ('behavior_score', models.FloatField(help_text='Score global 0-100 (moyenne équipondérée des 3 sous-scores).')),
                ('category', models.CharField(choices=[('bon', 'Bon payeur'), ('moyen', 'Payeur moyen'), ('mauvais', 'Mauvais payeur')], help_text='0-33: Mauvais · 33-66: Moyen · 66-100: Bon', max_length=10)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil comportemental client',
                'verbose_name_plural': 'Profils comportementaux clients',
                'db_table': 'client_behaviors',
                'ordering': ['-behavior_score'],
                'indexes': [models.Index(fields=['category'], name='client_beha_categor_2ed547_idx'), models.Index(fields=['type_client'], name='client_beha_type_cl_61f2f9_idx'), models.Index(fields=['behavior_score'], name='client_beha_behavio_6e2d67_idx'), models.Index(fields=['type_client', 'category'], name='client_beha_type_cl_8709de_idx'), models.Index(fields=['last_zone'], name='client_beha_last_zo_6652a0_idx'), models.Index(fields=['last_releveur'], name='client_beha_last_re_636924_idx')],
            },
        ),
    ]
