# Generated by Django 5.0.9 on 2026-05-04 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minio_key', models.CharField(help_text="Clé de l'objet dans le bucket MinIO (ex: fab/2026/04/fab20260412.txt).", max_length=255)),
                ('file_date', models.DateField(help_text="Date de l'extrait FAB (parsée depuis le nom de fichier fabAAAAMMJJ.txt).")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('nb_lines_total', models.IntegerField(blank=True, help_text='Nombre de lignes totales du FAB brut.', null=True)),
                ('nb_clients_kept', models.IntegerField(blank=True, help_text='Nombre de clients retenus après filtrage métier.', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si status=failed.")),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import FAB',
                'verbose_name_plural': 'Imports FAB',
                'db_table': 'fab_imports',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['status'], name='fab_imports_status_3a08e4_idx'), models.Index(fields=['file_date'], name='fab_imports_file_da_adb6ee_idx')],
            },
        ),
    ]
