# Generated by Django 5.0.9 on 2026-05-18 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fabimport',
            name='source',
            field=models.CharField(choices=[('manual', 'Upload manuel'), ('s3_auto', 'Sync S3 quotidienne'), ('s3_backfill', 'Backfill historique S3')], default='manual', help_text='Origine de cet import : upload manuel ou sync auto depuis S3.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fabimport',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec'), ('empty', 'Vide (FAB SNDE sans contenu utile)')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fabimport',
            index=models.Index(fields=['source'], name='fab_imports_source_e1b5d4_idx'),
        ),
    ]
