# Generated by Django 5.0.9 on 2026-05-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_fabimport_source_alter_fabimport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabimport',
            name='nb_clients_total',
            field=models.IntegerField(blank=True, help_text='Nombre total de clients ingérés en DB (tous codes de relance avec solde>0).', null=True),
        ),
        migrations.AlterField(
            model_name='fabimport',
            name='nb_clients_kept',
            field=models.IntegerField(blank=True, help_text="Nombre de clients scorés (code_relance='1' + toutes les conditions).", null=True),
        ),
    ]
